language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=flake

install:
    - sudo apt install ansible
    - pip install tox

before_script:
    - ansible --version

script: tox
